### PR TITLE
Provide url to user before launching the server

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by Ivoah** [comment]
I tried adding this feature before, but I couldn't get it to work, thanks for the PR.

**Comment by Ivoah** [comment]
This doesn't seem to work on Pythonista 2.0

```
[Errno 8] nodename nor servname provided, or not known
```

I'm reverting this PR until we find something that works.

**Comment by cclauss** [comment]
Try this one.

https://github.com/cclauss/WebIDE/commit/ec98f0b40b2b96a06da1d11f0c36e0fae0a3ce9d

It is not about the Pythonista version.  It is about how your lan router is set up.  See the notes in https://docs.python.org/2/library/socket.html#socket.gethostname

**Comment by Ivoah** [comment]
Done

**Pull request merged**
